debug: true
logging:
  config: "classpath:logback/logback-spring-@profileActive@.xml"
  file:
    path: ./logs/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/foundation_framework_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000ms
  flyway:
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # 是否启用flyway
    enabled: true
    locations: classpath:db/migration
    # 是否按顺序迁移 开发建议 true  生产建议 false
    out-of-order: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 1
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
knife4j:
  enable: true
  production: false
  setting:
    enableAfterScript: true
    enableDocumentManage: true
    enableRequestCache: true
    enableVersion: true
