debug: false
logging:
  config: "classpath:logback/logback-spring-@profileActive@.xml"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://域名:3306/health_evaluation_online?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    database: 1
    host: 127.0.0.1
    password: snHu2DnOkT1pXPZFUaei4hcIRwVhDB2A
    port: 6379
    timeout: 10000ms
  flyway:
    clean-disabled: true
    enabled: false
    locations: classpath:db/migration
    out-of-order: true
    baseline-version: 1
    baseline-on-migrate: true
knife4j:
  enable: true
  production: true
  setting:
    enableAfterScript: true
    enableDocumentManage: true
    enableRequestCache: true
    enableVersion: true
